#!/bin/bash

# Execute api calls

API_DIR="$HOME/api"

# Validation 1
#TODO: handle missing dir

# Validation 2
[[ -z "$@" ]] && >&2 echo "NEED SCRIPT NAME:" && ls -1 $API_DIR && exit 1

# EXECUTE
$API_DIR/$@

# Note:
# presentation is up to the script itself
