#!/bin/bash

yel="\e[33m"
red="\e[31m"
bold="\e[1m"
none="\e[0m"
key="O──┬┬"

main(){
  [[ $# -eq 0 ]] && echo -e "$yel""To decrypt files:$bold decrypt <file>...$none"
  for file in $@; do
    is_exist $file
    _decrypt $file
  done
}

is_exist() {
  if [[ ! -e "$1" ]]; then
    >&2 echo -e "$yel""file $1 does not exist$none"
    exit 1
  fi
}

_decrypt() {
  # send output to tmpfile
  tmp_file=$(mktemp -t decrypted.XXXX)
  gpg --decrypt --quiet "$file" > $tmp_file
  if [[ $? -eq 0 ]]; then
    >&2 echo -e "$bold$file $none $yel$key $none $bold$tmp_file $none"
  else
    >&2 echo -e "$red$bold""fail""$none"
  fi
}

main "$@"
