#!/bin/bash

# get various values and print them on screen as YAML/JSON/CSV/PP

main() {
  parse "$@" # parse using parse rules
    case "$1" in
        "") list_options ;;
        debug   | -d) debug_this_script ;;
        help    | -h) shift ; show_help "@" ;;
        connection | database | table) sql get ;;
        context) context get ;;
        os | system) echo "WSL (THIS IS AN EXAMPLE ONLY.)" ; exit 0 ;;
        *) unknown_arg_interpreter "$@" ;;
    esac

    # Process should not reach this point, if it does, maybe forgot exit
    echo -e "\e[31mERROR\e[0m" >&2
    exit 1
}

main "$@"
