#!/bin/bash

echo -en "\nLocal: "
# get ip oneliner
ip route get 1.1.1.1 | awk -F"src " 'NR == 1{ split($2, a," ");print a[1]}'

echo -n "Public: "
curl ipinfo.io/ip

echo -n "Router: "
192.168.2.1

echo -e "\n"
