#!/bin/bash

VERSION="3.4.0"

echo "Installing JetBrains Mono version $VERSION in 3 seconds..."
sleep 3

wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v${VERSION}/JetBrainsMono.zip \
&& cd ~/.local/share/fonts \
&& unzip JetBrainsMono.zip \
&& rm JetBrainsMono.zip \
&& fc-cache -fv
