#!/bin/bash

# entry fdc97cf0: Installation instructions for Docker and LubeLogger
# |
# 
# These steps assume Docker is already installed, such is the case with Aran
# 
# 1. pacman -S docker-compose
# 2. mkdir ~/src/lubelogger
# 3. cd ~/src/lubelogger
# 4. create .env file according to LubeLogger docs
# 5. copy https://github.com/hargata/lubelog/blob/main/docker-compose.yml
# 6. sudo systemctl start docker
# 7. sudo docker pull ghcr.io/hargata/lubelogger:latest
# 8. docker compose up -d
# 9. firefox localhost:8080

DATA="$AUTOKNIGHT_DIR" # ~/nexus/auto
BROWSER='firefox'
BROWSER_OPTS='--new-window'
PORT=8080
URL="localhost:$PORT"
IMAGE_URL="ghcr.io/hargata/lubelogger:latest" # for sudo docker pull <IMAGE_URL>

main(){
  run_docker_daemon
  # grab_sudo_permission
  launch_browser &
  start_container
}

#FIXME
grab_sudo_permission(){
  sudo echo "Permission granted"
}

run_docker_daemon(){
  sudo systemctl start docker
}

start_container(){
  cd "$DATA"
  sudo docker compose up
}

# FIXME: bad practices
launch_browser(){
  sleep 2
  $BROWSER "$BROWSER_OPTS" "$URL"
  sleep 3
  wmctrl -r "LubeLogger" -b toggle,maximized_vert,maximized_horz
}

main
