#!/bin/bash

JSON=$(parse "$@")
ARGS='.args.parsed'
COUNT=$#
COMMIT_MSG="committed via script: nexus"

dir_list='eza --header --all --long --icons --no-permissions --no-user --git --git-repos --total-size --time-style=relative --sort Name --hyperlink'

declare -a modules=(
  'task'
  'pass'
  '.'
)

main() {
  init
  execute
  terminate
}

init() {
  echo "$JSON" | jq
  cd $NEXUS
}

execute() {
  if [[ $COUNT -eq 0 ]]; then
    $dir_list
  elif _true $(_get push); then
    git_push_nexus
  elif _true $(_get pull); then
    git_push_nexus
  else
    echo 'huh?'
  fi
}

terminate() {
  :
}

git_push_nexus() {
  for module in "${modules[@]}"; do
    cd "$NEXUS/$module"
    git add .
    echo -n "$module: "
    git commit --short -m "$COMMIT_MSG"
    git push
  done
}

_get() {
  echo "$JSON" | jq "$ARGS.$1" -r
}

_true() {
  [[ "$1" == 'true' ]]
}

main
