#!/bin/bash

tsv= # stores TSV data
files= # stores list of file paths
report= # full report

while [[ $# -gt 0 ]]; do
  if [[ ! -f "$1" ]]; then
    echo "file $1 does not exist."
  else
    tsv+="$(cat $1)\n"
    # files+="$(realpath $1), "
  fi
  shift
done

# Extract the header and style it (bold + magenta + underline)
header=$(echo -e "$tsv" | head -n 1 | awk -F$'\t' '{for (i=1; i<=NF; i++) printf "\033[1;35;4m%s\033[0m\t", $i; print ""}')
# Extract the rest of the TSV data (without the header)
body=$(echo -e "$tsv" | tail -n +2)

# Combine the styled header with the body, then render
echo -e "$header\n$body" | column -t -s$'\t' | less --RAW-CONTROL-CHARS --chop-long-lines --shift=4 --quit-if-one-screen --no-init --tilde --LONG-PROMPT
