#!/bin/bash

tsv= # stores TSV data
files= # stores list of file paths
report= # full report

while [[ $# -gt 0 ]]; do
  if [[ ! -f "$1" ]]; then
    echo "file $1 does not exist."
  else
    tsv+="$(cat $1)\n"
    # files+="$(realpath $1), "
  fi
  shift
done

echo -e "$tsv" | column -t -s$'\t' | less -RS
