#!/bin/bash

separate() { echo "==================================================================================================== $*" ;  }
git-pull() { git --no-pager -C "$1" pul $2; }

separate NEXUS
nexus --pull
separate dotfiles
git-pull "$CONFIG" 1
separate archives
git-pull "$HOME/archives" 1
separate bin
git-pull "$HOME/bin" 1
separate pass
git-pull "$NEXUS/pass" 1
separate notes/wiki
git-pull "$HOME/wiki" 1
# separate coin
# git-pull "$HOME/src/coinmaster" 2
# separate jrnl
# git-pull "$HOME/src/journal" 2
# separate vita
# git-pull "$HOME/src/vita" 2
