#!/bin/bash

separate() { echo "==================================================================================================== $*" ;  }
git-pull() { git --no-pager -C "$1" pul $2; }

separate NEXUS
nexus --pull
separate dotfiles
git-pull "$CONFIG" 5
separate archives
git-pull "$HOME/archives" 3
separate bin
git-pull "$HOME/bin" 5
separate pass
git-pull "$NEXUS/pass" 2
# separate coin
# git-pull "$HOME/src/coinmaster" 2
# separate jrnl
# git-pull "$HOME/src/journal" 2
# separate vita
# git-pull "$HOME/src/vita" 2
